### ISSUE TITLE
If the phone is not rooted and you try to enable the toggle, the app crashes

### ISSUE THREAD

**Issue by aha999** [biqqles/p2oggle#3]
I don't have a rooted device (i know i should have for this) and when i press the toggle button in the app, the app crashes.
Instead it could say "could not enable the toggle" or something like that, instead of crashing.

**Comment by biqqles** [comment]
Thanks for reporting this, and sorry for the late reply. This is something the app is meant to do currently (as with all my root-required apps) but the topic has frequently given me trouble. Part of the reason is that the behaviour with Magisk disabled is completely different to no superuser utility being installed at all so it can be difficult to test.

**Comment by biqqles** [comment]
@aha999,what ROM are you on? I got round to testing this on Lineage 16 and I don't get a crash with Magisk uninstalled.

Edit: never mind, should have reset app data!

**Comment by aha999** [comment]
Sorry for late reply, just seen the comment, but i was on Lineage 16 without root at that time...
